name: python-ci
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.14"
    - name: Build front
      run: |
        npm install
        npm run build
    - name: flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --extend-exclude venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: mypy
      run: |
        # run mypy without raising error  
        mypy amstramdam || true
    - name: Test with pytest
      run: |
        pytest